### PR TITLE
Process's API

### PR DESCRIPTION
**Pull request by ziyue-pan**
# Done 9/9

- [x] `GetAllDepartments()`
- [x] `GetDepartmentByID()`
- [x] `CreateRegistration()`
- [x] `GetRegistrations()`
- [x] `GetRegistrationByID()`
- [x] `UpdateRegistrationStatus()`
- [x] `CreateMileStoneByDoctor()`
- [x] `UpdateMileStoneByDoctor()`
- [x] `DeleteMileStoneByDoctor()`

### CODE REVIEW

**Comment by ziyue-pan** [comment]
We simplify two function, `GetRegistrations` and `GetRegistrationByID`, merge the doctor's fetch and the patient's fetch

**Comment by AsterNighT** [comment]
a problem is that Doctor and Patient is not available now from account group. You may have to talk about that.

**Comment by ziyue-pan** [comment]
> a problem is that Doctor and Patient is not available now from account group. You may have to talk about that.

What do you mean by 'not available', something wrong with out APIs? or there are future modifications that will cause problems to our APIs' functionalities?

---

We have tested most situations, including 'working as a patient' and 'working as a doctor', seems there are nothing wrong with the functionalities.

**Comment by AsterNighT** [comment]
There is nothing in Doctor or Patient now. There's only Account.

**Comment by ziyue-pan** [comment]
> There is nothing in Doctor or Patient now. There's only Account.

Yes. As we have talked, Doctor and Patient will be maintained manually ...

**Review by RupertPaoZ — APPROVED** [review]

**Review by AsterNighT — APPROVED** [review]

**Pull request merged**
