### PR TITLE
implement chat

### PR DESCRIPTION
**Pull request by Estrella142857**
change into echo format

### CODE REVIEW

**Comment by AsterNighT** [comment]
pls fix your checks

**Comment by Frank-Skywalker** [comment]
If we don't need to use all MessageTypes in switch case, how can we forbid the error " missing cases in switch of type MessageType: MSG_FROM_SERVER, NEW_PATIENT, SEND_MEDICAL_RECORD, SEND_PRESCRIPTION, SEND_QUESTIONS (exhaustive)"

**Comment by AsterNighT** [comment]
> missing cases in swi

In that case, what are those enums for?

**Comment by Frank-Skywalker** [comment]
We'll use those types when sending back message to let clients know the type of this message.

**Comment by AsterNighT** [comment]
> We'll use those types when sending back message to let clients know the type of this message.

If they are used in different scenario, you could separate it into two types of enums like `ClientMessageType` and `ServerMessageType`

**Comment by Frank-Skywalker** [comment]
> > We'll use those types when sending back message to let clients know the type of this message.
> 
> If they are used in different scenario, you could separate it into two types of enums like `ClientMessageType` and `ServerMessageType`

okkkkkkkkkkk

**Comment by AsterNighT** [comment]
There are still many warnings. Those should not be too difficult to fix?

**Comment by Estrella142857** [comment]
If you mean those in checks, they seem to be part of another group's code. In that case, should we fix them?





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月6日(星期天) 晚上7:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AsterNighT/software-engineering-backend] implement chat (#30)





 
There are still many warnings. Those should not be too difficult to fix?

**Comment by AsterNighT** [comment]
oops, I didn't update the changes. LGTM now.

**Review by AsterNighT — APPROVED** [review]

**Pull request merged**
